name: default
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  REPOSITORY: firebase-tools
  VERSION: 9.18.0
  IMAGE: ${{ secrets.DOCKER_USER }}/${{ env.REPOSITORY }}
  TAG: ${{ secrets.DOCKER_USER }}/${{ env.REPOSITORY }}:${{ env.VERSION }}

jobs:
  firebase-tools:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: >
          docker build . --no-cache --pull
          -t ${{ env.TAG }}
          -t ${{ env.TAG }}-alpine
          -t ${{ env.IMAGE }}:latest
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          --build-arg VERSION=${{ env.VERSION }}
          --build-arg GITHUB_WORKFLOW=${{ env.GITHUB_WORKFLOW }}
          --build-arg GITHUB_RUN_ID=${{ env.GITHUB_RUN_ID }}
          --build-arg GITHUB_RUN_NUMBER=${{ env.GITHUB_RUN_NUMBER }}
          --build-arg GITHUB_JOB=${{ env.GITHUB_JOB }}
          --build-arg GITHUB_ACTION=${{ env.GITHUB_ACTION }}
          --build-arg GITHUB_EVENT_NAME=${{ env.GITHUB_EVENT_NAME }}
          --build-arg VCS_REF=${{ env.GITHUB_SHA }}

      - name: Publish the Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: >
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ env.TAG }}-alpine
          docker push ${{ env.TAG }}
          docker push ${{ env.IMAGE }}:latest
