name: default
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  pull_request:
    branches:
      - "**"

env:
  REPOSITORY: andreysenov/firebase-tools
  VERSION: 11.7.0

jobs:
  firebase-tools:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}

    strategy:
      matrix:
        context:
          [
            { dockerfile: Dockerfile, node: node-lts, os: alpine },
            { dockerfile: Dockerfile.node16, node: node-16, os: alpine },
            { dockerfile: Dockerfile.node14, node: node-14, os: alpine },
          ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: >
          docker buildx build . --no-cache --pull
          --platform linux/amd64,linux/arm64
          -f ${{ matrix.context.dockerfile }}
          -t ${{ env.REPOSITORY }}:${{ env.VERSION }}-${{ matrix.context.node }}
          -t ${{ env.REPOSITORY }}:${{ env.VERSION }}-${{ matrix.context.node }}-${{ matrix.context.os }}
          -t ${{ env.REPOSITORY }}:latest-${{ matrix.context.node }}
          -t ${{ env.REPOSITORY }}:latest-${{ matrix.context.node }}-${{ matrix.context.os }}
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          --build-arg VERSION=${{ env.VERSION }}
          --build-arg VCS_REF=${{ github.sha }}
          --push
