name: default
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

env:
  REPOSITORY: firebase-tools
  VERSION: 9.18.0

jobs:
  firebase-tools:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: >
          docker build . --no-cache --pull
          -t ${{ secrets.DOCKER_USER }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
          -t ${{ secrets.DOCKER_USER }}/${{ env.REPOSITORY }}:${{ env.VERSION }}-alpine
          -t ${{ secrets.DOCKER_USER }}/${{ env.REPOSITORY }}:latest
          --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          --build-arg VERSION=${{ env.VERSION }}
          --build-arg GITHUB_WORKFLOW=$GITHUB_WORKFLOW
          --build-arg GITHUB_RUN_ID=$GITHUB_RUN_ID
          --build-arg GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER
          --build-arg GITHUB_JOB=$GITHUB_JOB
          --build-arg GITHUB_ACTION=$GITHUB_ACTION
          --build-arg GITHUB_EVENT_NAME=$GITHUB_EVENT_NAME
          --build-arg VCS_REF=$GITHUB_SHA

      - name: Publish the Docker image
        if: ${{ github.event_name != 'pull_request' }}
        run: >
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USER }}/${{ env.REPOSITORY }}:${{ env.VERSION }}}-alpine
          docker push ${{ secrets.DOCKER_USER }}/${{ env.REPOSITORY }}:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USER }}/${{ env.REPOSITORY }}:latest
